### ISSUE TITLE
Update to vert.x 3.4.1 

### ISSUE THREAD

**Issue by millross** [pac4j/vertx-pac4j#106]
Update to vert.x 3.4.1 (currently on the 3.3.x version)

**Comment by leleuj** [comment]
Do you plan to do that before the release?

**Comment by millross** [comment]
Doesn’t matter, it won’t affect the pac4j release. We should not release vertx-pac4j without it though, but there will (and should) be a short time lag between the two releases, which should give me time to accommodate vert.x changes between 3.3 and 3.4. 

Don’t delay the pac4j release for it.

**Comment by leleuj** [comment]
Are they both major versions (I mean v3.3 and v3.4)? Because in that case, it would certainly be better to release:

- vertx-pac4j v3.0.0 based on pac4j v2.0.0 + Vert.x 3.3
- vertx-pac4j v3.1.0 based on pac4j v2.0.0 + Vert.x 3.4

?

**Comment by millross** [comment]
They are major versions, but we have already seen on the google group someone trying to use 3.4.1 of vert.x (although in a particularly ill-advised manner). I would suggest i make the attempt tomorrow and if it looks as though I can get everything passing by the weekend, we plan to release 3.0.0 next week with 3.4. If not, then we release sooner. Worst case, we release 3.0.0 early next week with 3.3 and 3.1.0 soon afterwards.

**Comment by leleuj** [comment]
OK. Ping me when you'll be ready for the release.

**Comment by millross** [comment]
Just ran a build against 3.4.1 and it looks promising. I’ll try and do some testing for the demo this evening as well :) If all looks ok I’ll push tomorrow.
