### ISSUE TITLE
Support for vertx3

### ISSUE THREAD

**Issue by meshuga** [pac4j/vertx-pac4j#11]
Are there any plans for vert.x 3 support? Version 3 contains many changes including concept changes (services with service proxies instead of modules), extended event bus, data objects etc., so it would require some serious code changes.

**Comment by leleuj** [comment]
This is something I have in mind, but I'd love to find contributors for that. Right now, I'm working on `pac4j` v1.8 and REST support, but I'll eventually upgrade to `Vertx` 3.

**Comment by millross** [comment]
This is now work in progress :)

**Comment by millross** [comment]
I think we can regard vert.x 3 as supported now.
