### ISSUE TITLE
some router when handled the SecurityHandler, I can't hander the request in my router handler.

### ISSUE THREAD

**Issue by aruis** [pac4j/vertx-pac4j#115]
some router when handled the SecurityHandler, 
I can't hander the request in my router handler.
 The error say 
`java.lang.IllegalStateException: Request has already been read 	at io.vertx.core.http.impl.HttpServerRequestImpl.checkEnded(HttpServerRequestImpl.java:437)`

my code like this:

    router.route().handler(securityHandler)
                .handler({ routingContext ->
            def request = routingContext.request()
            def response = routingContext.response()

            request.handler({ data ->
                println(data.toString())

            })

            request.endHandler({ data ->
                println("end:" + data.toString())
            })

            response.putHeader("content-type", "text/plain")
                    .end("ok")
        })

**Comment by aruis** [comment]
if I use this code ,it will be ok. But I don't know why.
![2018-05-18 15 52 45](https://user-images.githubusercontent.com/1785495/40222887-9e49cde8-5ab3-11e8-9639-06b857289b6a.png)

**Comment by leleuj** [comment]
Please ask your questions on the pac4j mailing lists.

**Comment by aruis** [comment]
ok thanks. I use the developer mailing lists and hope that this time I made no mistake.
