### ISSUE TITLE
Vert.x impl no longer supported?

### ISSUE THREAD

**Issue by aschrijver** [pac4j/vertx-pac4j#116]
Hi,

I've seen discussion on the Vert.x groups dating some time back, arguing that Pac4J should be the default security module for Vert.x. That didn't happen.

Now looking at the project, having the last real commit in Dec. 2016 and built against both an outdated Vert.x version as well as old Pack4J version, I conclude that this module is no longer actively supported.

Is that a correct assumption?
(I know... I am always welcome to submit my PR :wink: )

**Comment by leleuj** [comment]
@millross is currently inactive on this project and he was our main contributor. But this doesn't mean that this project is no longer maintained, it just means that evolutions will be much slower. It will be upgraded to pac4j v3.0.0 when it is released.

What you don't see here is the incredible work he has done, especially in trying to turn pac4j into a fully async framework (https://github.com/millross/pac4j-async). I failed to be supportive enough.

There is clearly a missed opportunity with the Vert.x community. I'm sure their help would have make a big difference.

**Comment by aschrijver** [comment]
Thank you for the info. I've read about the async work. Really appreciated!

Would be nice to see pac4j added to the official modules, at least

**Comment by leleuj** [comment]
Sure. This is something you can still propose...

**Comment by millross** [comment]
@leleuj You take more blame on this on himself than you should - you have far too much work to do on pac4j as it is, without taking ownership of the vertx impl. The bottom line is far more simple: last year I focused on the async work to try and get to a point where an async API could be defined. I did that, but towards the end of the year, other priorities took precedence (and continue to do so) over my spare-time work for the pac4j project, so I had to quit. There is nothing you could have done to prevent this, and you definitely did not fail to be supportive. 

Had the vertx-pac4j user base grown as I'd hoped during the 2 years I was maintaining the impl, then maybe someone else could have stepped up as maintainer, but it was still a very small group. The fact that @aschrijver is first to comment, almost 5 months after my departure, demonstrates exactly how small the appetite is for the vertx-pac4j implementation.
