### ISSUE TITLE
Update README to reflect vert.x 3 reality

### ISSUE THREAD

**Issue by millross** [pac4j/vertx-pac4j#12]
Update the README on master so it reflects the vert.x 3 situation (e.g. no longer a busmod, Clients object should currently be provided via code, rather than json config file)

Provide the URL of the 1.1.x code branch on github in the README for anyone who wishes to access it.

**Comment by millross** [comment]
Still outstanding:
Documentation for using the stateless handler

**Comment by leleuj** [comment]
One of the objectives behind pac4j 1.8 and its new implementations is offer the maximum consistency. Even in the README. So I tried to have the closest ones between J2E: https://github.com/pac4j/j2e-pac4j/blob/master/README.md and Play: https://github.com/pac4j/play-pac4j/blob/master/README.md.
It should be a good starting point for the this README as well.

**Comment by millross** [comment]
I was using the previous vertx-pac4j README as my template. I’ll add an issue to make it consistent with the others, but I’d rather not put too much time into that until I’ve actually made more progress on the code (otherwise I can see myself having to change the README regularly while the code’s still work in progress, given how limited my time is, unnecessary regular README updates strikes me as a poor investment). At the moment we still don’t even know if the code works properly because I haven’t even started on the demo yet, if it doesn’t the README is of very limited value.

**Comment by leleuj** [comment]
Sure. The README is the last step.

**Comment by millross** [comment]
Ah, I'd left this issue open because there was more work due on it anyway, was about to add a new issue with your comments but I'll keep this one open. Thanks :)

**Comment by leleuj** [comment]
@millross :
I decided to create a "family" of logos for all pac4j libraries: https://pac4j.github.io/pac4j/img/logo-j2e.png, https://pac4j.github.io/pac4j/img/logo-play.png, ... It's also a good way to draw attention on consistency.

And guess what? You have yours for Vertx: https://pac4j.github.io/pac4j/img/logo-vertx.png

How do you find it?

I'm expecting to see it at the top of the page (like for other implementations) unless you have any objection.

**Comment by millross** [comment]
Thanks, I’ve included this logo.
