### ISSUE TITLE
Update to latest vertx 3.6.2 

### ISSUE THREAD

**Issue by jsturgill** [pac4j/vertx-pac4j#122]
Please update to [vertx 3.6.2](https://github.com/vert-x3/wiki/wiki/3.6.2-Release-Notes).

**Comment by jsturgill** [comment]
Side note: code generation failed for my project using vertx 3.6.2 until I told gradle to ignore pac4j's dependency and force the desired version for all vertx dependencies.

I added this to the my `build.gradle`:

```
def vertxVersion = '3.6.2'

// force all vertx dependencies to a specific version
// remove when pac4j vertx updates
configurations.all {
    resolutionStrategy {
        eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'io.vertx') {
                details.useVersion vertxVersion
            }
        }
    }
}
```

**Comment by leleuj** [comment]
I just upgraded the master (version 4.1.0-SNAPSHOT) with Vert.x 3.6.2 and it builds without any issue (except a test I needed to fix). I also updated the demo.

I used version 4.1.0-SNAPSHOT (and not 5.0.0-SNAPSHOT) as Vert.x 3.6.2 seems to be backward compatible with Vert.x 3.5, but I'm not really sure about that...

**Comment by jsturgill** [comment]
Here is [the list of breaking changes](https://github.com/vert-x3/wiki/wiki/3.6.0-Deprecations-and-breaking-changes). There are not many that look like they would affect your project.

**Comment by leleuj** [comment]
No, I encountered no compile breaking changes. Only the handlersbar support has changed for the demo, but that's certainly not the only template engine option.

I'll re-test everything and cut a release next year if everything works...

**Comment by leleuj** [comment]
The release is available in the Maven central repository.
