### ISSUE TITLE
Upgrade to pac4j v4

### ISSUE THREAD

**Issue by leleuj** [pac4j/vertx-pac4j#139]

**Comment by leleuj** [comment]
@millross I hope you're well in these hard times.
I just wanted to let you know that I have made a huge upgrade and refactoring of the vertx-pac4j library (v5) by upgrading to pac4j v4: https://github.com/pac4j/vertx-pac4j/commit/14c16f068252097eea1753ef40d02c8a4dae1e85
Sorry for the tests removal, but there were disabled and I wasn't able to maintain them.
I updated the demo as well and my tests are ok.
If you have any time for testing or feedbacks...

**Comment by millross** [comment]
Hi Jérôme,

I’m doing fine, hope you are too. No need to apologise for maintaining the codebase as you see fit - its your code and if time doesn’t permit getting the tests working (not sure who disabled them, I certainly didn’t - I’m quite test-obsessed) then there’s not much else you can do. 

I wish I had time for testing/feedback, but really don’t at the moment. Hope pac4 is ticking along well.

Regards,

Jez
