### ISSUE TITLE
pac4jUserProfiles should not be stored as-is

### ISSUE THREAD

**Issue by nadenf** [pac4j/vertx-pac4j#145]
When using Vertx-Pac4J with certain cluster managers e.g. Redis it fails to save the session:

```
java.lang.IllegalStateException: Invalid type for data in session: class java.util.LinkedHashMap
	at io.vertx.ext.web.sstore.impl.SharedDataSessionImpl.writeDataToBuffer(SharedDataSessionImpl.java:144)
	at io.vertx.ext.web.sstore.impl.SharedDataSessionImpl.writeToBuffer(SharedDataSessionImpl.java:76)
```

This is because in ProfileManager, "pac4jUserProfiles" is being saved in the session as a LinkedHashMap which does not implement ClusterSerializable.

**Comment by jed204** [comment]
The release notes have v5.0.1 listed which has this fix. It looks like 5.0.0 is at maven central, are there plans to push 5.0.1 to central?

**Comment by leleuj** [comment]
I forgot. I just cut the v5.0.1 release, it will show up in the Maven central repository within a few hours.

**Comment by jed204** [comment]
Thanks!!
