### ISSUE TITLE
ClassCastException: java.lang.Long incompatible with java.util.Date

### ISSUE THREAD

**Issue by jed204** [pac4j/vertx-pac4j#156]
Exception is being thrown here:

```
at org.pac4j.oidc.profile.OidcProfile.getExpiration(OidcProfile.java:173)
```

Which is this code:
```
    public Date getExpiration() {
        return (Date) getAttribute(OidcProfileDefinition.EXPIRATION);
    }
```

The OidcProfile class assumes the 'expiration' attribute is in the date format which is how it starts. When it get serialized in the Pac4JUserProfiles class it's being converted to JSON first. When the JSON is deserialized the attributes are loaded in as a Long. This impacts any attribute that is a Date.

I've noticed this when utilizing the AzureAdOidcProfile (there are multiple dates stored with this profile)

I'm not too familiar with this library so looking for some guidance on how best to create a fix for this situation.

Thanks

**Comment by leleuj** [comment]
I think we should simply test if it's a `Long` to perform the right conversion. Something like:

```java
    public Date getExpiration() {
        final Object value = getAttribute(OidcProfileDefinition.EXPIRATION);
    if (value instance of Long) {
        return new Date(Long.parse(value));
    } else {
        return (Date) 
    }
```

Please open a PR for the pac4j project: https://github.com/pac4j/pac4j

**Comment by leleuj** [comment]
I just committed: https://github.com/pac4j/pac4j/commit/ac524dbdfb1082dd67281a34f22318e6f4d9a431

I added a `getAttributeAsDate ` method to be used wherever it's necessary.
