### ISSUE TITLE
Migrate code from Vertx 3.x to 4.x

### ISSUE THREAD

**Issue by rgmz** [pac4j/vertx-pac4j#174]
#### Description

Vert.x 4.x deprecated or removed several components currently used by vertx-pac4j. A [complete migration guide is available here](https://github.com/vert-x3/vertx-4-migration-guide/); however, I'll try to summarize (what I think are) the necessary changes.

**Changes required:**

- [ ] `AuthHandlerImpl` was removed; change [`SecurityHandler`](https://github.com/pac4j/vertx-pac4j/blob/f95b2174da8abcfb4f8fcc0aa069db07b7efea53/src/main/java/org/pac4j/vertx/handler/impl/SecurityHandler.java#L29) to inherit from `AuthenticationHandlerImpl` or `AuthorizationHandlerImpl`?
- [ ] `AuthProvider` was deprecated; change [`Pac4jAuthProvider`](https://github.com/pac4j/vertx-pac4j/blob/f95b2174da8abcfb4f8fcc0aa069db07b7efea53/src/main/java/org/pac4j/vertx/auth/Pac4jAuthProvider.java#L17) to inherit from `AuthenticationProvider`?
- [ ] `AbstractUser` was deprecated; change [`Pac4jUser`](https://github.com/pac4j/vertx-pac4j/blob/f95b2174da8abcfb4f8fcc0aa069db07b7efea53/src/main/java/org/pac4j/vertx/auth/Pac4jUser.java#L25) to extend `UserImpl`?
- [ ] [The `io.vertx.ext.web.Cookie` interface was removed](https://vert-x3.github.io/vertx-4-migration-guide/index.html#_removed_the_cookie_interfaces); replace with `io.vertx.core.http.Cookie`. 
- [ ] Generated rx extensions like `AyncMap#getClusterWideMapObservable` don't exist anymore; change [`VertxClusteredMapStore`](https://github.com/pac4j/vertx-pac4j/blob/f95b2174da8abcfb4f8fcc0aa069db07b7efea53/src/main/java/org/pac4j/vertx/core/store/VertxClusteredMapStore.java#L38) to use the new `rxGet` and `rxPut` methods? (The current codes use Observable, so I'm not sure if Single is comparable.)

**Comment by leleuj** [comment]
We have a PR for the migration: https://github.com/pac4j/vertx-pac4j/pull/161/files
Maybe this should go further...

**Comment by leleuj** [comment]
A new PR was proposed: https://github.com/pac4j/vertx-pac4j/pull/177
I just merged it on master (v6.x), feel free to complement it...
