### ISSUE TITLE
Investigate possible use of ProfileManager in Pac4j 

### ISSUE THREAD

**Issue by millross** [pac4j/vertx-pac4j#20]
At present the vert.x auth providers must be separate because they encapsulate dealing with the web session.

Investigate using the ProfileManager for this, and if possible, switch to its use. This might mean that we can have a single Pac4jAuthProvider for vert.x which simply rejects so that the underlying vertx-pac4j subsystem can take care of authentication fully. Pac4j offers the abstractions we want to use, so it makes 
sense to make use of those.

**Comment by millross** [comment]
Looks like we can use ProfileManager for both handlers, which will mean we can remove the session handling responsibility from the AuthProvider.

Note we should extend the Pac4j handler options class, to include the following possible parameters:-
ClientName,
Use Session For Direct Client

Also we need to raise additional tasks for other config elements to be added to the Pac4jHandlerOptions class (see j2e-pac4j for details).

**Comment by leleuj** [comment]
Thanks for sharing your thoughts and giving me the opportunity to push my own vision.

In fact, I plan to remove the `userSessionForDirectClient` parameter (from pac4j v1.8 and from the implementations). I'd like you not to use it, but I'm open to discussion of course.

The idea is to keep pac4j implementations really simple (not many concepts), focused on default flows and extensible for advanced use cases.
Direct clients should not use the session, but the request to store the user profile. So there should be no default option (like `userSessionForDirectClient`) to tweak that. Though, in the implementation, a `protected` method should return if the session must be used which would be then "overridable" for edge use cases:

```
protected boolean useSession(final WebContext context, final Client client) {
  return client == null || client instanceof IndirectClient;
}
```

would be overrided by:

```
@Override
protected boolean useSession(final WebContext context, final Client client) {
  return true; // always use session even for direct client
}
```

I will also remove the `allowDynamicClientSelection`: one more concept which makes things harder while the `clientName` could have a list of client names when it is necessary. To find the right client, you should use the https://github.com/pac4j/pac4j/pull/255/files#diff-b96b9ec49fc893afe0c425b05b03393aR30 (it should be changed only rarely by providing a new implementation)

I will remove `requireAnyRole` and `requireAllRoles` as well: the `RequireAnyRoleAuthorizer` and `RequireAllRolesAuthorizer` should be used instead.

I'll start updating the reference (J2E, Play) implementations next week.

**Comment by millross** [comment]
Thanks Jérôme,

I think that will make life easier for me :) The use of session for a direct client does indeed feel like an edge case , and broadly speaking unnecessary, but I'm happy to offer a mechanism where, if a developer wants to use it, they can inherit from my handler and override. 

The role requirement I want to look at in more detail on the vert.x side as I don't think vert.x offers the "require any role" approach, but I think I can override that and again delegate everything to the pac4j subsystem (which would be ideal, since the coder would just set up a Pac4j configuration and everything would be handled by that).

I'll keep an eye on the reference implementations as I work on these elements, to try and stay as close as is reasonably possible (i.e. as close as I can without making the codebase messy) to them.

**Comment by leleuj** [comment]
You're right: there was no "requireAnyRole" option in Vertx. I think I remember Vertx handles authorizations, so maybe you don't need to care about the `Authorizer` part in pac4j.

**Comment by millross** [comment]
I actually think it might be better to use Pac4j authorization though. I can use the profile to determine whether a permission/role is granted on vert.x's part but alternatively (and I'm considering which I prefer) it might be better to override auth when using a Pac4j-based handler to use the Pac4j subsystem so someone who is already familiar with Pac4j knows what to expect from the Pac4j configuration they've provided.

In other words, we allow the vert.x part to delegate as much as possible to the Pac4j side of things, with a note that "what vert.x offers by default is this, so if you want to just mirror vert.x, this is how you configure it, but you have other options available to you as well". Think about it this way, if we could make Pac4j fully reactive and non-blocking via the approach we've floated previously, there's a possibility that the existing vert.x auth might be retired in favour of just using Pac4j for everything (why reinvent the wheel?) 

The main argument against that is specifically that Pac4j blocks for certain i/o operations, so with a truly non-blocking API, I for one would push to use Pac4j as the basis for all vert.x auth unless someone has a particularly unusual use-case which Pac4j can't fulfil easily (in which case I suspect the existing vert.x auth wouldn't fulfil it easily either)

**Comment by leleuj** [comment]
It seems a really good plan to me!

**Comment by leleuj** [comment]
I just pushed the simplified design: https://github.com/leleuj/j2e-pac4j/blob/j2e-13/src/main/java/org/pac4j/j2e/filter/RequiresAuthenticationFilter.java

This is what I had in mind: few concepts, easy to understand, predictable behaviours, safe by default.

**Comment by millross** [comment]
Thanks

Is there any reason why you use instanceof checks based on the client type instead of two slightly different subclasses? It seems to me that the client could be identified as direct or indirect very early meaning that you could have a stateless child handler and a stateful child handler (getting most of their code from a common parent) and have the stateless handler complain if an indirect client is used or comparable for the stateful one. I have a fairly pathological hatred of instanceof checks to determine behaviour if it makes more sense to use polymorphism/inheritance.

Cheers,

Jez

**Comment by leleuj** [comment]
You raise a good point. I'm not sure it would make things easier to read and understand, which is my main objective. I have the feeling that the behaviour implemented in the `RequiresAuthenticationFilter` exists outside of the client itself, but I'm open to any suggestion.
Give it a try on the j2e-pac4j library with a "fake" PR if you want...

**Comment by millross** [comment]
I actually find code easier to read and understand where the Direct vs Indirect behaviour is captured in two different handler subclasses rather than shared in one, but maybe I’m in the minority. 

However, if it would ever make sense to use a direct client with a stateful behaviour or an indirect client with a stateless behaviour then if clauses based on type in a common handler class are required anyway (though that code could be put into some kind of plugin determined based on the client type when we set up the handler). 

If, however, there is no situation where you would use a direct client in a redirect-based authentication flow, or an indirect one without a redirect-based authentication flow then to me the codebase is cleaner and more legible by having a different handler subclass (from a parent RequiresAuthenticationHandler) for each of those, with those pieces of code where we currently use a client type check isolated down in those subclasses. When I read a conditional based on type, I find it harder, rather than easier, to read the code, especially if they appear in more than one place. 

How about for now, while I’m making the changes to pac4j-vertx, I do it with separate subclasses and then you can review the PR and determine whether you still think it’s harder to read. I’ll do it in such a way that I can easily turn things back into conditionals based on type if we decide that’s preferable :)

Cheers,

Jez

**Comment by leleuj** [comment]
Sure. Let's give it a try to see if we can improve design that way...

**Comment by millross** [comment]
Thanks, I think I’ve already come up with a slightly better approach, but let me try and express it in code first, and then we can talk about it when I’m ready to PR :) What I have in mind isolates the direct vs indirect client code better, without making it part of the handler (so the handler isn’t tightly coupled to a specific client). Let me get something working first as I’m virtually rewriting what’s in the handler anyway to make it consistent with the other implementations, then we’ll discuss. Hopefully it won’t end up being ugly :)

**Comment by millross** [comment]
Also refactored into something much closer to the play-pac4j implementation.
