### ISSUE TITLE
UserConverter.decode NPE when deserializing default constructed Pac4JUser

### ISSUE THREAD

**Issue by jpenglert** [pac4j/vertx-pac4j#246]
`Pac4jUser` has a default constructor which does not initialize its base class (`UserImpl`) `authorizations`, `attributes`, or `principal` fields. The `UserConverter` class expects `User` to return a non-null value for those fields. If an instance of `UserImpl` is constructed using the default constructor and then later on serialized (since it implements `ClusterSerializable`) and then deserialized it will result in a NPE when it delegates serialization to `UserConverter` because `UserConverter` does not perform a null check on the fields it's decoding from the given `JsonObject`.

I encountered this with the `Pac4jUser` class from `org.pac4j:vertx-pac4j` which extends `UserImpl` and implements the default constructor which leaves all the fields null. The `VertxProfileManager` from org.pac4j:vertx-pac4j uses the Pac4jUser default constructor.

See [vertx-auth issue 657](https://github.com/eclipse-vertx/vertx-auth/issues/657)

@tsegismont from vertx-auth suggested:

> My opinion is VertxProfileManager in Pac4j shouldn't invoke an internal constructor in UserImpl. Instead, it should one of the creation methods in the User interface.

Thoughts from the vertx-pac4j team on this?

**Comment by jpenglert** [comment]
@leleuj is looks like you last worked on `VertxProfileManager`. What do you think?

**Comment by jpenglert** [comment]
Made [PR 247](https://github.com/pac4j/vertx-pac4j/pull/247) that avoids all the NPEs caused by io.vertx.ext.auth.impl.UserConverter.

**Comment by leleuj** [comment]
It makes sense. I just merged the PR.

**Comment by leleuj** [comment]
I let you test and confirm that everything is OK with the version 6.0.2-SNAPSHOT before cutting the release.

Ping me when you're done.

**Comment by leleuj** [comment]
I just released vertx-pac4j v6.0.2: it will show up in the Maven central repository within a few minutes/hours...
