### ISSUE TITLE
Play-Pac4j

### ISSUE THREAD

**Issue by rayacode** [pac4j/vertx-pac4j#275]
First why issues on play-pac4j is closed?!
[https://stackoverflow.com/questions/78655666/xssprotection-noframe-nosniff-not-present-on-every-request](url)

I have a custom httpActionAdabter and i match matchers once also in the action adapter pac4jcsrf token and other matchers only will be present on register login and logout what i do to have them on all request? i tried using security filter and make matches these matchers on all request but it doesn't affect it in security logic with logs i see them that are included in requests in webcontext and in browser inspect element i can't see response header unless on callback url.

Using pac4j v6 and playframework v3
there is a issue with pac4j on play, matchers must get called manually on httpactionadabter to work but this only add response headers to callback urls not other urls, response headers are in webcontext both in SecureAction and SecurityLogic, but not at java request in browser. is it a bug? or it is the way actually it works?!
@leleuj 

i for now removed security filter of pac4j and added play play.filters.headers.SecurityHeadersFilter
    play.filters.hosts.AllowedHostsFilter to be get sure if it's a bug or not please answer it, thank you

**Comment by leleuj** [comment]
Issues are closed as most people just open one and never follow-up.

I saw your PR (https://github.com/pac4j/play-pac4j/pull/671), waiting for the build to pass.

**Comment by rayacode** [comment]
thank you @leleuj please open it i help with play pac4j and answer people issues on play-pac with java as i'm actively developing web app using play java and pac4j, i also keep contributing

**Comment by leleuj** [comment]
Sure. It's done

**Comment by rayacode** [comment]
thank you
