### ISSUE TITLE
When available use new components for finding correct client and auth check

### ISSUE THREAD

**Issue by millross** [pac4j/vertx-pac4j#40]
Jérôme is adding new components for the above purpose, once they're available use them in the vert.x-pac4j implementation

**Comment by leleuj** [comment]
https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/client/DefaultClientFinder.java
and
https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/authorization/DefaultAuthorizationChecker.java
