### ISSUE TITLE
Maven dependency in Readme file is wrong

### ISSUE THREAD

**Issue by pinyin** [pac4j/vertx-pac4j#43]
GroupId should be `org.pac4j.vertx` instead of `org.pac4j` for 2.0.0-SNAPSHOT

https://github.com/pac4j/vertx-pac4j#dependencies-1

 :)

**Comment by leleuj** [comment]
For consistency (with other implementations), the `groupId` is always `org.pac4j`.

**Comment by millross** [comment]
Updateed groupId in the pom.xml file
