### ISSUE TITLE
User in vertx-web.session is null

### ISSUE THREAD

**Issue by HendrikLanghammer** [pac4j/vertx-pac4j#55]
I always null for the webUser in a SocksJSHandler BridgeEvent: 

SockJSHandler sockJSHandler = SockJSHandler.create(vertx);
sockJSHandler.bridge(options, be -> {
  if (be.socket().webUser() == null) {
    // no active session, no game
    be.complete(false);
...

I think this is because the UserHolder for the vertx session does not get filled.

I worked around this issue by using be.socket().webSession().data().get(Pac4jConstants.USER_PROFILE) to get the Pac4j profile instead of using be.socket().webUser()

Unfortunately this issue breaks the vertx-web documentation when using Pac4jAuthProvider.

**Comment by millross** [comment]
Thanks, please could you supply a simple test which demonstrates this? I don't know the SockJS bridge stuff very well so any help will be very welcome.

**Comment by millross** [comment]
(Ideally a small github project I can just clone and run tests would be ideal)

**Comment by millross** [comment]
Just a note: I won't release 2.0 until I believe this is fixed. It's definitely a release blocking issue as it appears to break use of pac4j with vertx SockJS support.

**Comment by HendrikLanghammer** [comment]
OK, I'm on it, give me an hour or so.

**Comment by millross** [comment]
Thanks - there’s no immediate rush dude - vertx-pac4j is a spare time project for me and i’m on another release-blocker right now (hoping to clear it, and maybe this issue too this weekend)

**Comment by HendrikLanghammer** [comment]
I sent a pull request with a propable simple solution that works well for me with SocksJS bridge too.

**Comment by millross** [comment]
Thanks very much Hendrik. 

A couple of notes to myself (so I don't forget):-

(1) Ensure fix works for both direct and indirect clients
(2) Ensure that where we're using a UserSessionHandler (which auto-writes vertx user to session) the vertx user stored properly supports clustered sessions
(3) Ensure that external logout trigger (e.g. via Cas logout handler) triggers removal of the vertx user as well as Pac4j user - otherwise Cas logout requests from Cas server will not achieve desired result. Work for this trigger is currently WIP and expected to be complete before I start on this fix, if I shelve that work to work on this, I must add these notes to the Cas logout handler.

**Comment by HendrikLanghammer** [comment]
You're welcome and thanks for your work!

**Comment by millross** [comment]
Your PR is merged, and I've resolved the issue ahead of this one in the queue, so this is the next vertx-pac4j issue I work on. Once I've fixed this so it works as I want (which will incorporate some, maybe all, of your PR) you'll probably need to re-test to ensure it still works ok for you.

**Comment by HendrikLanghammer** [comment]
Thanks Jez! Of course I will retest and report when you managed to include the complete solution. It just might be that this cannoz happen before January as I go to holidays soon.

**Comment by millross** [comment]
The longer-term solution is now in progress.

**Comment by millross** [comment]
Hi Henrik, the longer-term solution is now merged and pushed. It should be a superset of your solution, so be warned that your next build will include these changes and you may wish to re-test and flag up any issues you run into (I hope there will be none, of course).

**Comment by HendrikLanghammer** [comment]
Hi Jez and happy new year! Unfortunately I have to report that the new version is not working for me. I have these lines
----
VertxWebContext webContext = new VertxWebContext(routingContext);
ProfileManager profileManager = new ProfileManager(webContext);
if (profileManager.isAuthenticated()) {
----
where profileManager.isAuthenticated() always returns false. I think this is because now there is no routingContext.session.data[pac4jUserProfile] in the new version.

What I see in the new version though is, that at this point routingContext.user is no longer null, so I could simply use this and be happy. What do you think?

**Comment by millross** [comment]
You need to use VertxProfileManager now. This wraps the vertx user correctly. Sorry, I wasn’t aware that you were using ProfileManager externally (that’s not intended usage)

routingContext.user() should always be correctly populated now.

Cheers,

Jez

**Comment by HendrikLanghammer** [comment]
Of course it's working perfectly using the VertxProfileManager - thank you!

**Comment by millross** [comment]
I still need to update the vertx-pac4j README, I will make a note to reference use of the VertxProfileManager rather than just the default ProfileManager implementation if using a profile manager in client code.

**Comment by leleuj** [comment]
All pac4j library READMEs have a "Get the user profile" section where it can appropriately be explained.

**Comment by millross** [comment]
Thanks Hendrik,

I will shortly be correcting the vertx-pac4j README, I will make a note about use of the VertxProfileManager in preference to the pac4j default ProfileManager (and what the VertxProfileManager depends on).

Glad it’s all working for you (you should - I think - be able to trust the RoutingContext user as well, as the intent is that the VertxProfileManager writes to/reads from the routing context user.
