### ISSUE TITLE
Cluster serialization/deserialization of Pac4jUser round trip fails

### ISSUE THREAD

**Issue by millross** [pac4j/vertx-pac4j#65]
As noted on PR https://github.com/pac4j/vertx-pac4j/pull/64 (which doesn't fix things the way I want), cluster serializing a Pac4jUser via writeToBuffer then deserializing via readFromBuffer fails with the following error 

Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.pac4j.core.profile.UserProfile
at org.pac4j.vertx.auth.Pac4jUser.readFromBuffer(Pac4jUser.java:85)
at io.vertx.ext.web.handler.impl.UserHolder.readFromBuffer(UserHolder.java:76)

Resolve this by continuing to use Json-based serialization, also include test to avoid regressions

**Comment by llfbandit** [comment]
I still have the issue in version 2.0.1 in a clustered environment:

Problem while reading DataSerializable, namespace: 0, id: 0, class: 'io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMap$DataSerializableHolder', exception: Failed to load class io.vertx.core.VertxException: java.lang.ClassCastException: java.lang.String cannot be cast to org.pac4j.core.profile.UserProfile

**Comment by millross** [comment]
Please provide a link to a simple github project which I can use to demonstrate the problem. Or alternatively please supply a unit test which shows it.

We have a specific test for this serialisation/deserialization which demonstrated the original problem and which now passes. at https://github.com/pac4j/vertx-pac4j/blob/master/src/test/java/org/pac4j/vertx/auth/Pac4jUserTest.java <https://github.com/pac4j/vertx-pac4j/blob/master/src/test/java/org/pac4j/vertx/auth/Pac4jUserTest.java> - so basically I’m going to need more help to investigate if you’re still experiencing the problem (JUnit based test would be ideal).

**Comment by llfbandit** [comment]
Sorry you can close again, I thought that the issue was handled in 2.0.1 but it's not the case.

**Comment by millross** [comment]
Really quite frustrated that github appears to have removed all previous comments :( 

The one which gave rise to the link request was:

"I still have the issue in version 2.0.1 in a clustered environment:

Problem while reading DataSerializable, namespace: 0, id: 0, class: 'io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMap$DataSerializableHolder', exception: Failed to load class io.vertx.core.VertxException: java.lang.ClassCastException: java.lang.String cannot be cast to org.pac4j.core.profile.UserProfile"

from llfbandit

**Comment by millross** [comment]
Let me check commit history, I thought it was resolved in the 2.0.1 release.

**Comment by millross** [comment]
You're correct, it's not in a release. I've just branched to start work on including pac4j1.9 which is substantial work, so I would prefer that you don't have to wait for that release to use. Please bear with me and we'll sort out a 2.0.2 release for you.

**Comment by llfbandit** [comment]
Thanks for the quick release. It's fixed in 2.0.2.
