### ISSUE TITLE
Multiple auth mechanisms

### ISSUE THREAD

**Issue by llfbandit** [pac4j/vertx-pac4j#66]
Hi,

I try to implement multiple auth mechanisms with form and oauth for now but I can't figure out hox to to do that.

Here's my pseudo implementation:
final FormClient formClient = new FormClient("http://localhost:8080/auth/", new FormAuthenticator());
final TwitterClient twitterClient = new TwitterClient("twId", "twSecret");

final Clients clients = new Clients("http://localhost:8080/callback", twitterClient, formClient);
final Config config = new Config(clients);

CallbackHandler callbackHandler = new CallbackHandler(vertx, config);
        router.get("/callback").handler(callbackHandler);
        router.post("/callback").handler(BodyHandler.create().setMergeFormAttributes(true));
        router.post("/callback").handler(callbackHandler);
Pac4jAuthHandlerOptions options = new Pac4jAuthHandlerOptions().withClientName("twitter");
router.get("/protected/*").handler(new RequiresAuthenticationHandler(vertx, config, (Pac4jAuthProvider) authProvider, options));

the endpoint for the form longin is given threw with constructor, but how to setup an endpoint to tell I want to be logged in with Twitter ?

Thanks for your help.

**Comment by millross** [comment]
Have you looked at vertx-pac4j-demo? That has multiple endpoints protected by different clients, including one endpoint protected by Facebook and twitter clients.

https://github.com/pac4j/vertx-pac4j-demo <https://github.com/pac4j/vertx-pac4j-demo>

Cheers,

Jez

**Comment by millross** [comment]
Basically for each path you want to protect differently you need to add an additional RequiresAuthenticationHandler. 

https://github.com/pac4j/vertx-pac4j-demo/blob/master/src/main/java/org/pac4j/vertx/verticle/DemoServerVerticle.java <https://github.com/pac4j/vertx-pac4j-demo/blob/master/src/main/java/org/pac4j/vertx/verticle/DemoServerVerticle.java>

and

https://github.com/pac4j/vertx-pac4j-demo/blob/master/src/main/java/org/pac4j/vertx/handler/DemoHandlers.java <https://github.com/pac4j/vertx-pac4j-demo/blob/master/src/main/java/org/pac4j/vertx/handler/DemoHandlers.java>

Cheers,

Jez

**Comment by millross** [comment]
Won't close this till I know you've achieved what you want.

**Comment by llfbandit** [comment]
Yes, but I still don't understand the logic with the demo.
I try to get a unique login page for form login and oauth providers.
How to make the route to auth with twitter?

**Comment by millross** [comment]
I’ll have to get back to you on this, I’m at work at present so can’t keep investing time during the day.

Please can you explain clearly in terms of what resources you want to protect (and via which method) and what you want your login page to look like. When I have some free time I’ll try and create an example for you if vertx-pac4j-demo isn’t sufficient (I’d appreciate some detail on what you’re failing to understand about the logic with the demo as well please, so maybe we can clarify in the demo).

**Comment by bdremynoel** [comment]
Ok I didn't see the double reference when setting up a route. Now I understand what's going on.

Is there any dedicated callback when the authentication flow is "full" processed and finished?
I need to backup some of the profile info, and the authentication route will be called each time the user will trigger the route even if he's already authenticated. This could hep to not hit the DB or setup a flag.

**Comment by millross** [comment]
The way you would do this (not really a pac4j concern, more a vert.x approach) would be to add another handler on the same route after the RequiresAuthenticationHandler which reads the user from the RoutingContext, extracts the profile info you wish to extract and stores it wherever you want. You could use the session for this, and then you just check the session to determine whether or not you’ve already set this information. 

If the user is already authenticated, he gets stored in the session, if you use the standard vert.x approach for doing this (again demonstrated in the vertx-pac4j-demo), the first check in the requires auth handler is to determine whether we already have an authenticated user, so you don’t go through the whole process every time.

**Comment by llfbandit** [comment]
Ok thanks

**Comment by millross** [comment]
Again I won't close this until you've achieved what you want. However, if you use UserSessionHandler you should find the vert.x user (which wraps the pac4j profile you authenticated with) automatically available via the routing context. 

So your handler chain for protected URLs would look something like 
(1) RequiresAuthenticationHandler (against, for example "/protected/*")
(2) Your custom handler (against the same url pattern) for storing whatever profile info you want, on successful auth (or identifying the user is already authenticated, the RAH calls RoutingContext::next()) so this handler will then be called. Once your handler has done what it needs, it should also call RoutingContext::next() or you won't reach the actual protected resources
(3) The handler which delivers the actual protected resources

I'm happy to take a look at anything you try if you can share it via Github (suggest it should be easy to extract anything commercially sensitive to try the pattern out, you can, for example, reuse the app information for facebook or twitter for your oauth handler).

**Comment by llfbandit** [comment]
Thanks for all your time. I'm ok with this. It's now on our own to better handle this and not let the user to be able to sign in twice. This case should not be possible.

**Comment by millross** [comment]
I think under pac4j 1.8 if the user signs in with oAuth and then tries to sign in with Form I’d expect that the form attempt would decide that the user was already signed in and just use the oAuth profile. In pac4j 1.9 I think a user can be signed in with multiple profiles simultaneously (you might want to ask on the pac4j google group about this).

I’d just like to clarify though - if you have a protected landing page you could set things up (with a pretty simple vert.x setup I think) so that if the user hits 

“http://mysite/ <http://mysite/>“ or similar, your handler just checks whether the routing context user is non-null, and if so redirects to the landing page, if not redirect to the page with the various login options (form redirect/oauth/whatever). This isn’t that different to what the form redirect stuff in vert.x does under the hood - see http://vertx.io/docs/apidocs/io/vertx/ext/web/handler/RedirectAuthHandler.html <http://vertx.io/docs/apidocs/io/vertx/ext/web/handler/RedirectAuthHandler.html> (you may even be able to hook into this relatively directly with a bit of thought)

Hope this is useful

**Comment by millross** [comment]
If I get time today (unsure if I will, but I'll try and make some) I'll try and create a branch on vertx-pac4j-demo which demonstrates the approach I mean

**Comment by millross** [comment]
Work in progress at https://github.com/millross/vertx-pac4j-multiauth-redirect-demo - at the moment just a skeleton but I'll let you know when I think it's done enough to be worth you reviewing

**Comment by millross** [comment]
The sample above is mostly done. The only flaw (that I have found so far) is that in my sample right now, it's possible to hit the login page directly (meaning that a user can still find a way to log in again and replace their existing user). I'm investigating why this is, but will probably not progress it further today. 

It's worth your while reviewing the code there and understanding what it does, though there will be a change soon to fix the ability to hit the login page directly (this should only be possible if you don't have an authenticated user, if you have an authenticated user you should be redirected to the protected version of the home page). Suspect this is some stupid config error on my part :)

**Comment by millross** [comment]
(I've updated the README on that project to provide a little more useful information)

**Comment by millross** [comment]
The demo project for this is now complete - the error was because I was permitting browser-caching of protected resources meaning that the authentication flow wasn't being re-triggered when requesting those resources, meaning that the user wasn't actually being authenticated. All good for you to take a look at https://github.com/millross/vertx-pac4j-multiauth-redirect-demo now - feel free to ask questions on that project as they occur to you
