### ISSUE TITLE
Using CommonProfile with Google provider result in cast exception

### ISSUE THREAD

**Issue by llfbandit** [pac4j/vertx-pac4j#67]
Using CommonProfile profile = profileManager.get(true); on a Google profile for email attribute (profile.getEmail()) will fail because Google provider setup a Map for this and CommonProfile cast directly to String.

Version 2.0.2

**Comment by millross** [comment]
Isn’t this a core pac4j issue, not a vertx-pac4j issue?

**Comment by llfbandit** [comment]
Arf, yes, I thought it was vertx module because of VertxProfileManager
