### ISSUE TITLE
Direct client example

### ISSUE THREAD

**Issue by mavencode01** [pac4j/vertx-pac4j#69]
I configured my client on the OpenID Connect provider as bearer only but the sample app still tries to redirect.

Is there any configuration I need to specify in the sample application to support direct client?

**Comment by millross** [comment]
I thought the OIDC client was an indirect client. Suggest you ask on the google group for pac4j which client to use for OIDC bearer. It's not an application issue, nor is it a vertx-pac4j issue (unless Jérôme specifies otherwise).

**Comment by millross** [comment]
https://groups.google.com/forum/#!forum/pac4j-users is the group  you should be asking on.

**Comment by mavencode01** [comment]
Aha! Thanks @millross

**Comment by leleuj** [comment]
The `OidcClient` is an indirect client as it requires to log in remotely at the OpenID Connect server: it currently implements the "authorization code flow". "As bearer", I guess you need a `HeaderClient` to retrieve the header, configured with a `JwtAuthenticator` or some customization of it to decrypt the JWT.
