### ISSUE TITLE
Add multi-profile support for indirect clients to vertx-pac4j built on pac4j 1.9

### ISSUE THREAD

**Issue by millross** [pac4j/vertx-pac4j#72]
One of the features pac4j 1.9.1 brings with it is support for multiple profiles being logged in in the same web session.

For vert.x support this will require modification of the vert.x implementation as follows. Because vert.x only sees one logged in user and we want to use infrastructure provided by vert.x web libraries and stay consistent as far as possible with vert.x authorisation implementations, the Pac4jUser implementation in vertx=pac4j, which currently wraps a single Pac4j profile should be extended to wrap multiple Pac4j profiles. 

We will use existing implementations as a guide for how these internal profiles should be stored and retrieved, the only slight complication is the requirement to wrap them within something which vert.x will recognise as a User, but this should be feasible

**Comment by leleuj** [comment]
For me, it's just a matter of the `Pac4jUser` accepting a `LinkedHashMap`. Like: `Pac4jAccount` (https://github.com/pac4j/undertow-pac4j/blob/master/src/main/java/org/pac4j/undertow/account/Pac4jAccount.java) for example...

**Comment by millross** [comment]
I’m considering whether it needs to be concurrent, but the basic idea is that.

**Comment by millross** [comment]
Still more to do on this, but the lowest level building block is in place. Integration tests will be required to ensure that the multi-profile functionality behaves as expected when actually used.

**Comment by millross** [comment]
Reduced the scope of this issue to just cover multi profile support when indirect clients are used. Issue #79 deals with ensuring multi profile support works as expected for direct clients.

**Comment by millross** [comment]
Now completed multi profile support for indirect clients, as evidenced by a test which forces indirect login with an additional profile and tests the profiles in the pac4j user.
