### ISSUE TITLE
Security issue: upgrade to pac4j v1.9.4

### ISSUE THREAD

**Issue by leleuj** [pac4j/vertx-pac4j#78]
@millross : I have some tests failures when upgrading to pac4j v1.9.4. I guess I can let you handle that on your own.

**Comment by millross** [comment]
Update to 1.9.3 still in progress, I'll change the dependency when I'm stable enough to do so.

**Comment by millross** [comment]
(Still adding tests to ensure multiprofile is adequately supported. We shouldn't release until vertx-pac4j supports multiprofile and also depends on 1.9.4 though. I'll keep this open.

**Comment by millross** [comment]
Will address this once issue #72 (multi profile support with indirect clients) is complete.

**Comment by millross** [comment]
In progress: pa4cj 1.9.4 breaks ClusteredSharedDataLogoutHandlerIntegrationTest - I guess 1.9.4 isn't a drop-in replacement for 1.9.2.

**Comment by millross** [comment]
Looks like test failure was just a timeout because my machine was overloaded updating dependencies in IntelliJ IDEA. Memo to self: need a new personal laptop :)

**Comment by leleuj** [comment]
So pac4j 1.9.4 is really a drop-in replacement for 1.9.2: great! I would not have understood anything else.

**Comment by millross** [comment]
Yeah, was just a bit surprised because you got test failures, then I did following upgrade (but my personal laptop is getting very slow and it struggles with dependency changes in the IDE now). As far as vertx-pac4j goes, it certainly was a drop-in replacement.
