### ISSUE TITLE
Implement centralLogout in logoutHandler

### ISSUE THREAD

**Issue by millross** [pac4j/vertx-pac4j#88]
As part of the port to pac4j2, initial implementation just sets the centralLogoug parameter to false, for consistency with previous pac4j versions.  

Extend to actually store a centralLogout configuration element for the handler and apply it when calling the logout logic.

**Comment by millross** [comment]
Serious problem being experienced here, which could either be a thread-safety issue (WebContext), some weird short-circuit (response being received before the central logout handling finishes) or something wrong in the logout logic. Tests have been created though. This is going to have to wait till I have a several-hour block to look at it, this evening has soaked up pretty much all my vertx-pac4j time allocation for this week and next.

**Comment by millross** [comment]
Looks like this is happening because creating http actions via HttpAction factory methods has side effects (writing to the WebContext). DefaultLogoutLogic executes a default (200) action then try and replace it with a 302. It would be better if the logic created a supplier for the action, which was then only called in at the end of the method to generate the action to pass to the adapter.

However, in the meantime, I think I can change VertxWebContext to do a noop on write of empty string, which will resolve the issue (effectively writing to the response then trying to change the status code is the problem).

**Comment by leleuj** [comment]
Yes, creating `HttpAction` via the static methods writes on the web context. Keep me posted.

**Comment by millross** [comment]
If the side effecting behaviour becomes problematic in the longer term I know how to resolve it with a change to the DefaultLogics. However, for now I'll try my workaround in the VertxWebContext (sometime this week) and let you know how I get on. I'd like to get centralLogout finished very soon so I can start updating the demo, and then update to the latest vert.x ready for the next pac4j milestone release :)

**Comment by millross** [comment]
Build problem due to recent compatibility breaks in pac4j snapshot. I will resolve when I have time, but this may not be before Tuesday 28/03/17

**Comment by millross** [comment]
We've had to rollback from snapshot to build against pac4j 2.0.0-M1. Some of the changes in 2.0.0-M2 (and on SNAPSHOT over the past week) break vertx-pac4j.

So centralLogout is now supported, but for the time being if you wish to use it, you must use pac4j 2.0.0-M1.
